name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    name: Lint & Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    
    - name: Install dependencies
      run: bun install
    
    - name: Type checking
      run: bun run type-check
    
    - name: Lint code
      run: bun run lint
    
    - name: Test help command
      run: bun run help
    
    - name: Test individual steps help
      run: |
        echo "Testing individual step commands..."
        bun run step1 --help || echo "Step 1 completed (expected for backup script)"
        bun run step2 --help || echo "Step 2 completed (expected for reset script)"
        bun run step3 --help || echo "Step 3 completed (expected for parse script)"
        bun run step4 --help || echo "Step 4 completed (expected for filter script)"
        bun run step5 --help || echo "Step 5 completed (expected for save script)"

  cross-platform:
    name: Cross-platform compatibility
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    
    - name: Install dependencies
      run: bun install
    
    - name: Test help command
      run: bun run help
